name: CombatExpanded
version: 1.1
main: com.willy.combatexpanded.CombatExpanded
api-version: 1.21
author: WornOutWilly
description: "Adds Fun Movements & Skills."

commands:
  artifice:
    description: Toggles The New Combat System For Players
    aliases: a
  combatexpanded:
    description: Main commands for CombatExpanded
    aliases: ce

permissions:
  combatexpanded.artifice:
    description: Players can toggle the New Combat System
    default: true
  combatexpanded.admin:
    description: Allows admin commands of CombatExpanded
    default: op


depend:
  - PlaceholderAPI
  - BetterHud
