name: CombatExpanded
version: 1.0
main: com.willy.combatexpanded.CombatExpanded
api-version: 1.21
author: WornOutWilly
description: "Adds Fun Movements & Skills."

commands:
  artifice:
    description: Toggles The New Combat System For Players
    usage: /artifice
    aliases: [a, togglea, toggleartifice]
  ce:
    description: Main commands for CombatExpanded
    usage: "/ce reload | /ce enable | /ce disable"
    aliases: combatexpanded
    permission: combatexpanded.admin
    default: op

depend: []
softdepend: [PlaceholderAPI, BetterHUD]
